import { useEffect, useState } from 'react';
import { Activity, Bell, CheckCheck, ExternalLink, ThumbsDown, ThumbsUp, TrendingDown, TrendingUp, Zap } from 'lucide-react';
import { api, type AlertCitation, type AlertItem } from '../lib/api';
import { cn, fmtINR, tickerLabel, timeAgo } from '../lib/format';
import { useApp } from '../lib/user';
import { useToast } from './toast';
import { Badge, Button, Card, EmptyState, PageHeader, Segmented, Skeleton } from './ui';

const TYPE_META: Record<string, { label: string; icon: typeof Bell; tone: 'up' | 'down' | 'warn' | 'primary' }> = {
  STOP_LOSS_BREACH: { label: 'Stop-loss hit', icon: TrendingDown, tone: 'down' },
  TARGET_HIT: { label: 'Target hit', icon: TrendingUp, tone: 'up' },
  SENTIMENT_CRASH: { label: 'Sentiment drop', icon: Activity, tone: 'warn' },
  RSI_OVERBOUGHT: { label: 'RSI overbought', icon: Activity, tone: 'warn' },
  RSI_OVERSOLD: { label: 'RSI oversold', icon: Activity, tone: 'primary' },
  VOLUME_SPIKE: { label: 'Volume spike', icon: Zap, tone: 'warn' },
};

export default function Alerts() {
  const { refreshUnread } = useApp();
  const toast = useToast();
  const [alerts, setAlerts] = useState<AlertItem[] | null>(null);
  const [filter, setFilter] = useState<'all' | 'unread'>('all');
  const [voted, setVoted] = useState<Record<number, boolean>>({});

  const load = () => api<AlertItem[]>('/alerts').then(setAlerts).catch(() => setAlerts([]));
  useEffect(() => { load(); const iv = setInterval(load, 30000); return () => clearInterval(iv); }, []);

  const markRead = async (id: number) => {
    setAlerts(a => a?.map(x => (x.id === id ? { ...x, is_read: true } : x)) ?? a);
    await api(`/alerts/${id}/read`, { method: 'PATCH' }).catch(() => {});
    refreshUnread();
  };
  const markAll = async () => {
    const unread = (alerts ?? []).filter(a => !a.is_read);
    await Promise.all(unread.map(a => markRead(a.id)));
    toast('success', `Marked ${unread.length} alert${unread.length === 1 ? '' : 's'} as read`);
  };
  const vote = async (id: number, positive: boolean) => {
    setVoted(v => ({ ...v, [id]: positive }));
    try {
      await api(`/alerts/${id}/feedback`, { method: 'POST', body: JSON.stringify({ is_positive: positive }) });
      toast('success', 'Thanks for the feedback', 'It helps tune future alerts.');
    } catch { toast('error', 'Could not save feedback'); }
  };

  const shown = (alerts ?? []).filter(a => filter === 'all' || !a.is_read);
  const unreadCount = (alerts ?? []).filter(a => !a.is_read).length;

  return (
    <div className="mx-auto max-w-[900px] px-6 py-8 lg:px-10">
      <PageHeader title="Alerts" subtitle="Generated by the portfolio monitor every 15 minutes during market hours"
        actions={<>
          <Segmented value={filter} onChange={setFilter} options={[{ value: 'all', label: 'All' }, { value: 'unread', label: `Unread${unreadCount ? ` (${unreadCount})` : ''}` }]} />
          <Button variant="outline" onClick={markAll} disabled={!unreadCount}><CheckCheck className="h-4 w-4" />Mark all read</Button>
        </>} />

      {alerts === null ? <div className="space-y-3">{[0, 1, 2].map(i => <Skeleton key={i} className="h-24" />)}</div> : shown.length === 0 ? (
        <Card><EmptyState icon={<Bell className="h-5 w-5" />} title={filter === 'unread' ? 'No unread alerts' : 'No alerts yet'}
          body="Set stop-loss and target levels on your holdings to get notified." /></Card>
      ) : (
        <div className="space-y-3">
          {shown.map((a, i) => {
            const meta = TYPE_META[a.alert_type] ?? { label: a.alert_type.replace(/_/g, ' ').toLowerCase(), icon: Bell, tone: 'primary' as const };
            const Icon = meta.icon;
            return (
              <Card key={a.id} onClick={() => !a.is_read && markRead(a.id)} style={{ animationDelay: `${Math.min(i, 8) * 30}ms` }}
                className={cn('group flex gap-4 p-4 animate-fade-in-up transition-colors hover:border-border-strong', !a.is_read && 'cursor-pointer border-l-[3px] border-l-primary')}>
                <div className={cn('grid h-10 w-10 shrink-0 place-items-center rounded-xl',
                  { up: 'bg-up/10 text-up', down: 'bg-down/10 text-down', warn: 'bg-warn/10 text-warn', primary: 'bg-primary/10 text-primary' }[meta.tone])}>
                  <Icon className="h-5 w-5" />
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-semibold">{tickerLabel(a.ticker)}</span>
                    <span className="text-[13px] capitalize text-muted">{meta.label}</span>
                    <Badge tone={a.signal === 'SELL' ? 'down' : a.signal === 'BUY' ? 'up' : 'warn'}>{a.signal}</Badge>
                    <span className="ml-auto text-[12px] text-muted">{timeAgo(a.created_at)}</span>
                  </div>
                  <p className="mt-1 text-sm text-fg-2">{a.message}</p>
                  {(a.citations?.length ?? 0) > 0 && <Citations items={a.citations!} />}
                  <div className="mt-2 flex items-center gap-3">
                    {a.price_at_alert != null && <span className="text-[12px] text-muted tabular">Price at alert {fmtINR(a.price_at_alert)}</span>}
                    <div className="ml-auto flex items-center gap-1" onClick={e => e.stopPropagation()}>
                      <span className="mr-1 text-[12px] text-muted">Useful?</span>
                      <Button variant="ghost" size="icon-sm" disabled={a.id in voted} onClick={() => vote(a.id, true)} aria-label="Useful"
                        className={cn(voted[a.id] === true && '!text-up !opacity-100')}><ThumbsUp className="h-3.5 w-3.5" /></Button>
                      <Button variant="ghost" size="icon-sm" disabled={a.id in voted} onClick={() => vote(a.id, false)} aria-label="Not useful"
                        className={cn(voted[a.id] === false && '!text-down !opacity-100')}><ThumbsDown className="h-3.5 w-3.5" /></Button>
                    </div>
                  </div>
                </div>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}

function Citations({ items }: { items: AlertCitation[] }) {
  return (
    <div className="mt-2.5 rounded-lg border border-border bg-surface-2/40 p-2.5" onClick={e => e.stopPropagation()}>
      <div className="mb-1.5 text-[11px] font-medium uppercase tracking-wide text-muted">Sources</div>
      <ol className="space-y-1.5">
        {items.map((c, i) => {
          const meta = [c.source, c.published_at ? timeAgo(c.published_at) : null].filter(Boolean).join(' · ');
          return (
            <li key={i} className="flex items-start gap-2 text-[13px]">
              <span className="mt-px w-4 shrink-0 text-right text-[11px] tabular text-muted">{i + 1}</span>
              <div className="min-w-0 flex-1">
                {c.url ? (
                  <a href={c.url} target="_blank" rel="noreferrer" className="group inline-flex items-start gap-1 font-medium text-fg hover:text-primary">
                    <span>{c.title}</span><ExternalLink className="mt-0.5 h-3 w-3 shrink-0 opacity-50 group-hover:opacity-100" />
                  </a>
                ) : <span className="font-medium text-fg">{c.title}</span>}
                {meta && <div className="text-[11px] text-muted">{meta}</div>}
              </div>
              {typeof c.score === 'number' && (
                <span className={cn('shrink-0 rounded px-1.5 py-0.5 text-[11px] font-medium tabular',
                  c.score <= -0.15 ? 'bg-down/10 text-down' : c.score >= 0.15 ? 'bg-up/10 text-up' : 'bg-surface-2 text-muted')}
                  title="Article sentiment, -1 bearish to +1 bullish">{c.score > 0 ? '+' : ''}{c.score.toFixed(2)}</span>
              )}
            </li>
          );
        })}
      </ol>
    </div>
  );
}
